data:
  # train
  train:
    type: myzoneufc_coloradjust
    name: train_data
    data_transforms:
      - type: coloradjust_transform.generate_input_stats
      - type: to_tensor
      - type: collect
        inputs: [input_stats]
    data_loader:
      num_workers: 2
      batch_size: 64
    data_params:
      mode: train
  # validation
  val:
    type: myzoneufc_coloradjust
    name: val_data
    data_transforms:
      - type: coloradjust_transform.generate_input_stats
      - type: to_tensor
      - type: collect
        inputs: [input_stats]
    data_loader:
      num_workers: 2
      batch_size: 64
  # test
  test:
    type: myzoneufc_coloradjust
    name: test_data
    data_transforms:
      - type: coloradjust_transform.generate_input_stats
      - type: to_tensor
      - type: collect
        inputs: [input_stats]
    data_loader:
      num_workers: 2
      batch_size: 64
  # common
  data_params:
    input_size: [192, 256] # w,h
    input_channels: 3

model:
  type: coloradjust_model.color_adjustor
  backbone:
    type: dnn
    in_dims: 10
    out_dims: 6
    hidden_dims: 128
    depth: 4
  head:
    type: coloradjust_head.adjust_image
  loss:
    type: coloradjust_loss.stats_distance
  predict:
    type: coloradjust_postprocess.predict

complex_train:
  stations:
    # station 1
    - name: train_st
      threads:
        - name: train_th
          data: train
          start_outer_round: 1
          max_inner_epochs: 1
          max_epochs: 50
          global_vars: [epoch]
          terminate_inner_loop_when_closed: true
          will_terminate_outer_loop_when_finished: true
          optim:
            optimizer:
              type: adam
              lr: 0.0005
            lr_scheduler:
              type: step_lr
              by_epoch: true
              step: [30, 40, 45]
              gamma: 0.3
              warmup: linear
              warmup_ratio: 0.01
              warmup_steps: 200
            optim_scheduler:
              type: optim
          summarize:
            interval: 10
          save:
            by_epoch: true
            interval: 1
            max_keep_ckpts: 5
    # station 2
    - name: validate_st
      threads:
        - name: validate_th
          mode: val
          data: val
          max_inner_epochs: 1
          progressbar_unit: item
          validate:
            save_best_by: avg_stats_diff
            metric_greater_better: false
            save_prefix: val_
            evaluate_begin_kwargs:
              show_adjust_num: 20
          summarize:
            multiline_logging: true
            multiline_keywidth: 30
            multiline_valwidth: 10
            multiline_ncols: 4
